### PR TITLE
Report screenshot along with failed command

### LINKED ISSUE #19: Add a screenshot to failing command report
SDK should submit a step report with a screenshot when the driver command fails.

### PR DESCRIPTION
**Pull request by mstrelex**
Fixes #19 

This change requires Agent 0.63.13+

### CODE REVIEW

File: src/main/java/io/testproject/sdk/internal/rest/messages/DriverCommandReport.java [hunk 1]
```diff
@@ -43,6 +43,28 @@
...
+     */
+    public String getScreenshot() {
+        return screenshot;
+    }
+
+    /**
+     * Setter for {@link #screenshot} field.
+     * @param screenshot Screenshot (as base64 string) to be set.
+     */
+    public void setScreenshot(final String screenshot) {
```
Comment (vitalybu) [inline src/main/java/io/testproject/sdk/internal/rest/messages/DriverCommandReport.java:64]: The SDK actually takes the screenshot and passes it to the Agent?
Why not take the screenshot on the Agent's side?

Comment (mstrelex) [reply src/main/java/io/testproject/sdk/internal/rest/messages/DriverCommandReport.java:64]: Timing - reports are sent asynchronously and screenshot may not reflect actual UI state.

Comment (vitalybu) [reply src/main/java/io/testproject/sdk/internal/rest/messages/DriverCommandReport.java:64]: Makes sense. But screenshots can be large (MBs?), maybe the screenshot payload should be compressed instead of converted to base64?

Comment (mstrelex) [reply src/main/java/io/testproject/sdk/internal/rest/messages/DriverCommandReport.java:64]: It can reach several megabytes theoretically, however it's an intranet communication.
This is based on the same mechanism Selenium / Appium use - transfer the screenshot as base64 from server to client, and the same as we do when reporting getScreenshot command that has the screenshot data in it's parameters as base64 string.

Comment (vitalybu) [reply src/main/java/io/testproject/sdk/internal/rest/messages/DriverCommandReport.java:64]: Ok

**Review by vitalybu — APPROVED** [review]
